# amoCRM
AMOCRM_DOMAIN = 
AMOCRM_TOKEN = 
AMOCRM_CATALOG_ID =

# iiko
IIKO_API_KEY = 
IIKO_ORGANIZATION_ID = 
IIKO_TERMINAL_GROUP_ID = 
IIKO_MENU_ID = 
IIKO_BASE_URL = 
IIKO_MENU_URL = 

# Yandex
YANDEX_BASE_URL = "https://b2b.taxi.yandex.net/b2b/cargo/integration/v2"
YANDEX_API_KEY = 
